**Ue02 - 27.09.24 - Marius Lassl**

# ED I

## Collecting Data from PDF 

In [4]:
# documentation PyPDF: https://pypdf2.readthedocs.io/en/3.x/
import PyPDF2 as pypdf

with open ('Cyber-Sicherheit.pdf', 'rb') as pdf:
    reader = pypdf.PdfReader(pdf)

    # Doc-Info ausgeben
    print(reader.metadata)

    # Anzahl der Seiten ausgeben
    print(len(reader.pages))

{'/Author': 'Rechnungshof', '/CreationDate': "D:20220422095428+02'00'", '/Creator': 'Adobe InDesign 15.1 (Macintosh)', '/ModDate': "D:20220422105104+02'00'", '/Producer': 'Adobe PDF Library 15.0', '/Subject': 'GZ 2022-0.281.048 (004.920)', '/Title': 'Bericht des Rechnungshofes: Koordination der Cyber–Sicherheit', '/Trapped': '/False'}
114


### 2.1 Generieren Sie basierend auf dem Rechnungshofbericht zum Thema „Koordination der Cyber-Sicherheit2“ folgenden Output: 

Author: Rechnungshof Producer: Adobe PDF Library 15.0 Title: Bericht des Rechnungshofes: Koordination der Cyber–Sicherheit Hinweis: Die Verwendung von getDocumentInfo der Klasse PdfFileReader ist hierbei sicherlich kein Nachteil.

In [6]:
with open ('Cyber-Sicherheit.pdf', 'rb') as pdf:
    reader = pypdf.PdfReader(pdf)
    meta = reader.metadata

    print("Author: {} Producer: {} Title: {}".format(meta.author, meta.producer, meta.title))

Author: Rechnungshof Producer: Adobe PDF Library 15.0 Title: Bericht des Rechnungshofes: Koordination der Cyber–Sicherheit


### 2.2 Erweitern Sie die Ausgabe dahingehend, dass … 

'1) … der Text der ersten Seite ausgegeben wird. 2) … der gesamte Text ausgegeben wird. 3) … jede Seite des PDFs einer Liste hinzugefügt und am Ende ausgegeben wird. 

In [22]:
import PyPDF2

# Open the PDF file in binary mode
with open('Cyber-Sicherheit.pdf', 'rb') as pdf:
    reader = PyPDF2.PdfReader(pdf)

    # 1)
    #first_page= reader.pages[0].extract_text()
    #print(first_page)
    
    # 2)
    #all_pages = ''
    #for page in reader.pages:
    #    all_pages += page.extract_text()
    #print(all_pages)

    # 3)
    page_list = []
    for page in reader.pages:
        page_list.append(page.extract_text())

    nr = 1
    for page in page_list:
        print("\nSeite {} --------------------------------------------\n".format(nr))
        print(page)
        nr += 1
        
    


Seite 1 --------------------------------------------

III–623 der Beilagen zu den Stenographischen Protokollen des Nationalrates XXVII. GP
Rechnungshof GZ 2022–0.281.048 (004.920)Reihe BUND 2022/13Koordination der Cyber–Sicherheit
Bericht des Rechnungshofes

Seite 2 --------------------------------------------

Koordination der Cyber–Sicherheit
IMPRESSUM
Herausgeber:  
Rechnungshof Österreich
1030 Wien, Dampfschiffstraße 2www.rechnungshof.gv.atRedaktion und Grafik: Rechnungshof ÖsterreichHerausgegeben: Wien, im April 2022
AUSKÜNFTE
Rechnungshof
Telefon  (+43 1) 711 71 – 8946
E–Mail  info@rechnungshof.gv.at
facebook /RechnungshofAT
Twitter : @RHSprecherFOTOSCover: Rechnungshof/Achim BieniekVorbemerkungen
Vorlage
Der Rechnungshof erstattet dem Nationalrat gemäß Art. 126d Abs. 1 Bundes–
Ver fassungsgesetz nachstehenden Bericht über Wahrnehmungen, die er bei einer 
Gebarungsüberprüfung getroffen hat.
Berichtsaufbau
In der Regel werden bei der Berichterstattung punkteweise zusammenfassend 

## Collecting Data from HTML 

In [27]:
import urllib.request as urllib2 
from bs4 import BeautifulSoup 

response = urllib2.urlopen('https://www.htlkrems.ac.at') 
html_doc = response.read() 

In [29]:
# Website laden 
response = urllib2.urlopen('https://www.htlkrems.ac.at') 
html_doc = response.read() 

# Das BeautifulSoup Object soup repräsentiert das „geparste“ HTML-Dokument  
soup = BeautifulSoup(html_doc, 'html.parser') 

# Das „geparste“ HTML-Dokument formatieren, sodass jeder Tag bzw. Textblock 
# in einer separaten Zeile ausgegeben wird 
strhtm = soup.prettify() 

# Ein paar Zeilen ausgeben 
print (strhtm[:1000]) 

<!DOCTYPE html>
<html class="no-js" lang="de-DE">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width" name="viewport"/>
  <link href="http://gmpg.org/xfn/11" rel="profile"/>
  <link href="https://www.htlkrems.ac.at/xmlrpc.php" rel="pingback"/>
  <link href="#" rel="stylesheet" title="colors" type="text/css"/>
  <title>
   HTL Krems
  </title>
  <meta content="max-image-preview:large" name="robots">
   <!-- Open Graph Meta Tags generated by Blog2Social 801 - https://www.blog2social.com -->
   <meta content="HOME" property="og:title">
    <meta content="JTNDZGl2JTIwY2xhc3MlM0QlMjJoZXJvJTIyJTNFJTBB" property="og:description"/>
    <meta content="https://www.htlkrems.ac.at/" property="og:url"/>
    <meta content="website" property="og:type"/>
    <!-- Open Graph Meta Tags generated by Blog2Social 801 - https://www.blog2social.com -->
    <!-- Twitter Card generated by Blog2Social 801 - https://www.blog2social.com -->
    <meta content="summary" name="twitter:card"/>
    

In [33]:
#print(soup.title)
#print(soup.title.string)

HTL Krems


### 2.3 Gesucht ist der Text/Inhalt aller Anchor Tags (vgl. ) auf www.htlkrems.ac.at. Geben Sie diesen aus. Hierbei ist die soup-Funktion find_all() überaus hilfreich.¶

In [54]:
all_tags = soup.find_all('a')
for tag in all_tags:
    print(tag.string)

EduFlow
EduPay
WebUntis
Sprechstunden
NEWS
TERMINE
INTERN
None
None
None
None
None
ÜBER UNS
ÜBER UNS
NEWS
LEITUNG
Team
LEITBILD
Schulpartner/Vereine
SW_Weiz / Ingenium
Facebook
Instagram
KONTAKT
BAUTECHNIK
BAUTECHNIK
HÖHERE ABTEILUNG
HOCHBAU
TIEFBAU
HOLZBAU
KOLLEG BAUTECHNIK
FACHSCHULE
BERUFE/BERECHTIGUNG
BAUPRAXIS
NEWS BAUTECHNIK
INFORMATIONSTECHNOLOGIE
INFORMATIONSTECHNOLOGIE
SYSTEMTECHNIK
MEDIENTECHNIK
COMPUTERPRAKTIKUM
BERUFSAUSSICHTEN
NEWS IT
MEDIZININFORMATIK
SERVICE
Infos für SJ 2024/25
INTERN/LINKS
TERMINE
DOWNLOADS
BERATUNG
BILDUNGSBERATUNG
INDIVIDUELLE LERNBEGLEITUNG
SCHÜLERBERATUNG
JOBS
Praktika
Sprechstunden
None


None
None
Hochwasserschutz Rehberg und Anpassung HWS An der Schütt 
							
Baustellenbesichtigung der Firma Porr 
							


None
None
3AFBT in Budapest 
							
Kultur, Kulinarik und Public Viewing 
							


None
None
Werksbesichtigung bei Fertigteilhausfirma Elk 
							
1AFBT in Schrems 
							


None
None
Zu Besuch in der WU Wien 
							
Berufsorientierung

### 2.4 Ermitteln Sie basierend auf 2.3 die Anzahl der Hyperlinks.  

In [56]:
len(all_tags)

124

# ED II

https://www.w3schools.com/python/python_regex.asp

In [11]:
import re 
p = re.compile("5") 
print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt.")) 
print(p.findall("Für 5 Semmeln habe ich 5€ bezahlt.")) 

['5']
['5', '5']


In [44]:
p = re.compile("[1234567890]") # look for numbers from 0 to 9
p = re.compile("[0-9]") # alternative
#Output: ['5', '3', '9', '0']

p = re.compile(" [0-9] ") # take space into account
#Output: [' 5 ']

p = re.compile(r"[0-9]\.[0-9][0-9]") 

print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt.")) 

['3.90']


### 3.1 Gesucht ist ein Pattern, das den Betrag sowohl in Euro (€) als auch Dollar ($) extrahiert. Implementieren Sie zwei separate Ausgaben, sodass folgendes Ergebnis zu Buche steht: 

#['3.90€'] 
#['3.90$'] 

In [104]:
import re

p = re.compile(r"[0-9]+\.[0-9]{2}[€$]")  # r: raw string
print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt."))
print(p.findall("Für 5 Semmeln habe ich 3.90$ bezahlt.")) 
print(p.findall("Für 5 Semmeln habe ich 3.90§ bezahlt.")) 
print(p.findall("Für 5 Semmeln habe ich 3.900€ bezahlt."))

['3.90€']
['3.90$']
[]
[]


In [65]:
p = re.compile(" [0-9] ") 
print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt.")) 
print(p.findall("Für 15 Semmeln habe ich 19.50$ bezahlt.")) 
print(p.findall("Für 150 Semmeln habe ich 190.50$ bezahlt.")) 

[' 5 ']
[]
[]


### 3.2 Wäre das Pattern " [0-9][0-9][0-9] " eine mögliche Lösung? Begründen Sie Ihre Antwort. 

Nein, jetzt sind genau 3 Ziffern zwischen 0 und 9 erfoderlich! Nur 150 würde also matchen

In [74]:
p = re.compile(" [0-9][0-9][0-9] ") 
print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt.")) 
print(p.findall("Für 15 Semmeln habe ich 19.50$ bezahlt.")) 
print(p.findall("Für 150 Semmeln habe ich 190.50$ bezahlt.")) 

[]
[]
[' 150 ']


In [77]:
p = re.compile(" [0-9]+ ") 
print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt.")) 
print(p.findall("Für 15 Semmeln habe ich 19.50$ bezahlt.")) 
print(p.findall("Für 150 Semmeln habe ich 190.50$ bezahlt.")) 

[' 5 ']
[' 15 ']
[' 150 ']


In [102]:
p = re.compile(r" [0-9]+\.[0-9][0-9][€$] ")
print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt.")) 
print(p.findall("Für 15 Semmeln habe ich 19.50$ bezahlt.")) 
print(p.findall("Für 150 Semmeln habe ich 190.50$ bezahlt.")) 
#[' 3.90€ '] #[' 19.50$ '] #[' 190.50$ '] 

[' 3.90€ ']
[' 19.50$ ']
[' 190.50$ ']


### 3.3 Adaptieren Sie das Pattern so, dass die Preisextraktion unter den neuen Voraussetzungen ebenso gut funktioniert. Hinweis: Bei der letzten Zeichenkette ist statt dem Punkt ein Komma angeführt. Außerdem ging das Währungssymbol verloren.

* print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt."))
* print(p.findall("Für 15 Semmeln habe ich 19.50$ bezahlt."))
* print(p.findall("Für 150 Semmeln habe ich 190,50 bezahlt.")) 

In [134]:
p = re.compile(r" [0-9]+[.,][0-9]{2}[€$]* ") 
# + -> one or more
# * -> zero or more

p = re.compile(r" [0-9]+[.,][0-9]{2}[€$]{0,1} ")

print(p.findall("Für 5 Semmeln habe ich 3.90€ bezahlt."))
print(p.findall("Für 15 Semmeln habe ich 19.50$ bezahlt."))
print(p.findall("Für 150 Semmeln habe ich 190,50 bezahlt.")) 

[' 3.90€ ']
[' 19.50$ ']
[' 190,50 ']


In [136]:
p = re.compile("Telefonnummer") 
print(p.search("Meine Telefonnummer ist 0664 555 0 123. Ruf schnell an!")) 

<re.Match object; span=(6, 19), match='Telefonnummer'>


In [138]:
match = p.search("Meine Telefonnummer ist 0664 555 0 123. Ruf schnell an!") 
print(match.span()) 
print(match.start()) 
print(match.end())

(6, 19)
6
19


### 3.4 Neben den bereits bekannten Funktionen findall und search gibt es auch noch finditer und match, worin unterscheiden sich diese? 

**Zusammenfassung der Unterschiede**
* **findall**: Gibt eine Liste aller Vorkommen zurück. Gut für einfache Suchen ohne Bedarf an Positionsinformationen. 
* **search**: Findet das erste Vorkommen des Musters und gibt ein Match-Objekt zurück. Ideal für die Suche nach dem ersten Treffer. 
* **finditer**: Gibt einen Iterator von Match-Objekten zurück. Ermöglicht detaillierte Analysen der Übereinstimmungen, einschließlich der Positionen im Text. 
* **match**: Prüft nur, ob das Muster am Anfang des Textes übereinstimmt. Nützlich, wenn du überprüfen möchtest, ob der Text mit einem bestimmten Muster beginnt. 

**ODER Oprator |**

In [143]:
print(re.search("Frau|Herr", "Sehr geehrte Frau Musterfrau! Ich darf Sie darauf hinweisen, dass...")) 
print(re.search("Frau|Herr", "Sehr geehrter Herr Mustermann! Ich darf Sie darauf hinweisen, dass..."))

<re.Match object; span=(13, 17), match='Frau'>
<re.Match object; span=(14, 18), match='Herr'>


**Wildcard Operator .**

In [ ]:
re.findall(".und","Der Hund hat keinen Mund ") 

**Anfang ^ Ende $**

In [163]:
someText = ["a", "abc", "bac"] 
for text in someText:
    print(re.findall("^a", text)) 

['a']
['a']
[]


In [189]:
someNewText = ["a","formula","bac"] 
for text in someText:
    print(re.findall("a$", text)) 

['a']
[]
[]


### 3.5 Im Großen und Ganzen sollten der Zweck sowie die Funktionsweise von RegEx klar sein. Um die neu gelernten Inhalte zu festigen, arbeiten Sie das referenzierte Tutorial6 durch.  

https://www.programiz.com/python-programming/regex

### 3.6 Laden Sie die Startseite der www.htlkrems.at-Site und extrahieren Sie alle Mailadressen, die die Website beinhaltet. Speichern Sie diese in einer csv-Datei (1 Spalte mit der Adresse). Überlegen Sie, wie es prinzipiell möglich wäre, Adressen über mehrere Websites zu sammeln? 

In [253]:
import urllib.request as urllib2 
from bs4 import BeautifulSoup
import re
import csv

# WebScrapping aus vorheriger Übung
# -------------------------------------------------------------
def scrape_url(url):
    # Website laden 
    response = urllib2.urlopen(url) 
    html_doc = response.read() 
    
    # Das BeautifulSoup Object soup repräsentiert das „geparste“ HTML-Dokument  
    soup = BeautifulSoup(html_doc, 'html.parser') 
    
    # Das „geparste“ HTML-Dokument formatieren, sodass jeder Tag bzw. Textblock 
    # in einer separaten Zeile ausgegeben wird 
    strhtm = soup.prettify() 
    
    # Ein paar Zeilen ausgeben 
    #print (strhtm) 

    return print('--- Finished Scrapping URL---')
# -------------------------------------------------------------

def read_from_csv(filename):
    print('--- Printing E-Mails from CSV ---')
    with open(filename, newline='', encoding='utf-8') as csvfile:
        reader = csv.reader(csvfile)
        emails = [row[0] for row in reader]
    return emails
    
def write_to_csv(filename, emails):
    with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        for email in unique_emails:
            writer.writerow([email])
    return print('--- Finished writing E-Mails to CSV ---')




# Scraping htlkrems Website
scrape_url('https://www.htlkrems.ac.at')

# Extractin E-Mails 
email_pattern = r'[a-zA-Z0-9]+@[a-zA-Z0-9-]+\.[a-z]{2}'
emails = re.findall(email_pattern, soup.get_text())

# Writing E-Mails to CSV + Output
write_to_csv('emails.csv', emails)
emails = read_from_csv('emails.csv')
for email in emails:
    print(email)

--- Finished Scrapping URL---
--- Finished writing E-Mails to CSV ---
--- Printing E-Mails from CSV ---
office@htlkrems.at


### 3.7 Sie sind für die Datenaufbereitung in einem NLP-Projekt verantwortlich. Als Grundlage dient die Job-Seite7 der HTL Krems.   

a) Ziel ist die Extraktion und Ausgabe IT-relevanter Angebote im Notebook: 

In [273]:
# Liste von Schlüsselwörtern 
keywords = ['Developer', 'Entwickler', 'Entwicklung', 'Softwareentwickler', 'Programmierer'] 


def scrape_url(url):
    # Website laden 
    response = urllib2.urlopen(url) 
    html_doc = response.read() 
    
    # Das BeautifulSoup Object soup repräsentiert das „geparste“ HTML-Dokument  
    soup = BeautifulSoup(html_doc, 'html.parser') 
    
    # Das „geparste“ HTML-Dokument formatieren, sodass jeder Tag bzw. Textblock 
    # in einer separaten Zeile ausgegeben wird 
    strhtm = soup.prettify() 
    
    # Ein paar Zeilen ausgeben 
    #print (strhtm) 

    print(soup.find_all('td'))

def display_relevant_job_offers(relevant_jobs): 
    if relevant_jobs:
        for job in relevant_jobs:
            print("--------------------------------------------------")
            print(job)
            print("--------------------------------------------------")
    else:
        print(":(")
        
j = scrape_url('https://www.htlkrems.ac.at/jobs/')
display_relevant_job_offers(j)

[<td class="column-1">KASTNER Service GesmbH </td>, <td class="column-2"><a href="https://www.htlkrems.ac.at/wp-content/uploads/2024/10/KASTNER-Service-GesmbH_Junior-SoftwareentwicklerIn.pdf">Junior SoftwareentwicklerIn</a></td>, <td class="column-3">IT</td>, <td class="column-4">2024/10</td>, <td class="column-1">KASTNER Service GesmbH </td>, <td class="column-2"><a href="https://www.htlkrems.ac.at/wp-content/uploads/2024/10/KASTNER-Service-GesmbH_Trainee-IT-First-Level-Support.pdf">Trainee IT First Level Support</a></td>, <td class="column-3">IT</td>, <td class="column-4">2024/10</td>, <td class="column-1">Universität für Weiterbildung Krems (Donau-Universität Krems)</td>, <td class="column-2"><a href="https://www.htlkrems.ac.at/wp-content/uploads/2024/10/Universitaet-fuer-Weiterbildung-Krems-Donau-Universitaet-Krems_IT-MitarbeiterIn-mit-Schwerpunkt-Microsoft-Business-Applications.pdf">IT-MitarbeiterIn mit Schwerpunkt Microsoft Business Applications</a></td>, <td class="column-3">IT<

b) Speichern Sie die Einträge in einer CSV-Datei. Je nach Lösungsansatz, kann der Einsatz des csv-Moduls8 Sinn machen – bspw. dann, wenn man ein Dictionary9 ohne viel Aufwand in die csv-Datei schreiben möchte! Gesuchtes Ergebnis: 